### ISSUE TITLE
Don't look for NilClassPolicy

### ISSUE THREAD

**Issue by jnicklas** [elabs/pundit#251]
In case `authorize` receives `nil` it should just deny authorization, not look for `NilClassPolicy `. I can't imagine any situation where someone would actually want to implement `NilClassPolicy `.

**Comment by bendilley** [comment]
I'm actually dead against this change. To me it goes against the philosophy that Pundit is just a handful of helpers and an unopinionated style of doing things.

By example, in view logic, rather than having a nice, encapsulated
```ruby
class NilClassPolicy < ApplicationPolicy

  # Nobody can see nothing.
  def show?
    false
  end

end
```
which allows me to write in a view
```ruby
policy(object_which_might_be_nil).show?
```
I now have the inconvenience of having to check
```ruby
object_which_might_be_nil && policy(object_which_might_be_nil).show?
```
and I have to do that _everywhere_ I want to use `show?`, `edit?`, etc. with an object that could be nil.

I now can't use the [null object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern) with Pundit.

**Comment by jnicklas** [comment]
@bendilley that's actually a pretty good point.

**Comment by pendletons** [comment]
> I can't imagine any situation where someone would actually want to implement NilClassPolicy.

and https://github.com/elabs/pundit#just-plain-old-ruby seem at odds with each other. If the ethos is “you can do whatever you want with it, it's flexible!” then perhaps this feature should be an addition to the `README` on how to configure your own policies to disallow `nil`, rather than forcing the gem as a whole to ignore it.

**Comment by toshify** [comment]
I also miss being able to use the null object pattern with Pundit and would petition to have this change reversed.

**Comment by davegudge** [comment]
I would also like to see this change reversed.
