### ISSUE TITLE
RSpec matcher `permit` clashes with `shoulda-matchers`' `permit`

### ISSUE THREAD

**Issue by pusewicz** [elabs/pundit#270]
Both `shoulda-matchers` and `pundit` define `permit` matcher. How about changing it to `policy_permit`?

**Comment by jnicklas** [comment]
Please use the search, there are three separate issues for this already. #258, #145, #142.

tl;dr: Pundit is right, shoulda is wrong.

**Comment by hosh** [comment]
Wow, that's quite a thing to say there.

**Comment by hosh** [comment]
I dug into the code some more and I'm going to document things here for people who find this issue in the future. Maybe people just got tired of talking about this.

On the surface, it seems like Shoulda is the bigger project, and they are supporting a core Rails feature. But when looking into the code, Pundit isolates it's matchers:

https://github.com/elabs/pundit/blob/master/lib/pundit/rspec.rb#L66-L78

while Shoulda shotguns their matchers for everything:

https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/integrations/test_frameworks/rspec.rb#L12-L16

Looking at the design of the new shoulda-matchers 3.0, it was intended to be framework agnostic. They wrote adapters so that you can configure things. But since the adapter is passed an array of included modules, there's no clean way to do this. One way I can see it is iterating through the array, using a case statement to configure Rspec to enable the matchers for specific types of example groups. On one hand, that makes it brittle... on the other hand, there are only three major types of matchers (active_model, active_record, and active_controller).

I'm tempted to write a small gem that loads this correctly for rspec based on the example that is in Pundit. It does make the new Shoulda configuration code useless for Rspec ...well, unless shoulda-matchers are the only thing you are trying to use.

**Comment by hosh** [comment]
One more comment for those who come after. The solution to this doesn't need a gem. Instead of using the new `Shoulda.configure` interface, simply drop this into the `RSpec.configure` block of `rails_helpers.rb`:

```
# Make shoulda-matcher behave as a good rspec citizen
config.include(Shoulda::Matchers::ActiveModel, { type: :model, file_path: /spec\/models/})
config.include(Shoulda::Matchers::ActiveRecord, { type: :model, file_path: /spec\/models/})
config.include(Shoulda::Matchers::ActionController, { type: :model, file_path: /spec\/controllers/})
```

**Comment by sophiedeziel** [comment]
Wow @hosh , thanks!! I was looking for a solution two months ago and now you have it :)

**Comment by sophiedeziel** [comment]
Thanks @hosh , I was looking for a solution two months ago and now I have it!

However, this works only with the new shoulda-matchers version (3.0.0.rc1)
