### ISSUE TITLE
permitted_attributes should accept a symbol

### ISSUE THREAD

**Issue by scottjacobsen** [elabs/pundit#299]
In the same way that `authorize` accepts a symbol, it would be nice if `permitted_attributes` also accepted a symbol.

Because `permitted_attributes` only accepts an object you end up with some ugly chicken and egg code in `create` actions:

```ruby
def create
    authorize(:post)
   # Need a post before I can use permitted_attributes
   @post = Post.new
   @post.update_attributes permitted_attributes(@post)
   ...
end
```

This would be nicer:

```ruby
def create
   authorize(:post)
   @post = Post.new permitted_attributes(:post)
   ...
end
```

I would be happy to contribute a PR if that is something you would accept.

**Comment by jnicklas** [comment]
I don't think this is going to work. You'll usually need access to the post object inside the policy to authorize it. Same with permitted attributes.

**Comment by ce07c3** [comment]
I don't agree. When I create new records or search on a scope, I don't need a record.

**Comment by scottjacobsen** [comment]
I do often have cases where an object isn't required for the authorization. The authorization is based purely on the user's role. `create?` is usually like that. `index?` can often be.

It is more rare for `permitted_attributes` (I can only think of the `create?` case), but since `authorize` already works with a symbol it would give the API a nice symmetry if permitted_attributes could also take a symbol.

**Comment by victormier** [comment]
+1

**Comment by hachpai** [comment]
For me I do like that:
````
def permitted_attributes(model=nil)
    model ||= model_class #defined in the controller
    policy(model).permitted_attributes #can be invoked with a class, policy(User) for example
  end
````

**Comment by jezstephens** [comment]
I'm not sure doing `authorize(:post)` is the recommended technique in this situation, where there exists a `Post` model and the other query methods in your `PostPolicy` presumably accept an instance of such. The README suggests that using a symbol is intended for "headless" policies which do not relate to a particular model.

Ignoring "permitted attributes" for a moment, I'd do this:

```ruby
def create
  @post = Post.new(post_params) # Could be done in a before filter for new & create
  authorize(@post)
  @post.save
  ...
end
```

That said, while it's always meaningful to supply a fully initialized instance for action authorization, I'm not sure it ever makes sense to have to provide a blank instance to authorize attributes. Therefore I'm inclined to agree that it would be useful to allow a symbol to be passed instead.

**Comment by erlandsona** [comment]
I'm with @jezstephens. What's the word on this one? Currently I've refactored about 6 controllers into one super controller. They we're all very standard CRUD controllers and it made sense to refactor all the repetition into one BaseController. That said I had to use controller_name.classify.constantize to get the corresponding resource names to be CRUD'd which works great until you get to the create action which as described in previous posts pundit requires that you have an empty instance of the class you want to create before you can add attributes to that instance and it seems a bit counterintuitive to me?

**Comment by scottjacobsen** [comment]
I've stopped using the `permitted_attributes` helper. I don't really think it belongs in pundit. There are too many edge cases - an implementation that satisfies them all would be very complicated. It buys very little (maybe it saves a few lines of code per controller). It just feels like it has low cohesion with the rest of pundit - it seemed like a good idea at first but after some usage it does not work well. That's just my humble opinion.

I would close this issue since I opened it, but since several people have commented I'll let a pundit maintainer make that call.

**Comment by Silex** [comment]
It becomes even uglier when everyone is allowed to create its own user, but then you have authorization for the other methods (e.g `edit` etc).

The idea to centralize everything "security" with parameters in the policy is nice, but it doens't work very well in that case. This is what I had to use:

``` ruby
def create
  @user = User.new(params.require(:user).permit(*Pundit.policy!(User.new, User.new).permitted_attributes))
  # ...
end
```

**Comment by RST-J** [comment]
I just started using Pundit in a new project and have exactly the same issue in create actions. I wondered, whether there is a solution I just didn't find yet but this issue makes me believe there isn't.
Is there an elegant way (like in don't create dummy instances) to use ``permitted_attributes`` for initialization? I'm currently going for this solution:
```ruby
@foo = Foo.new
@foo.assign_attributes permitted_attributes(@foo)
authorize @foo
```

I'm not very into the question whether determining allowed parameters belongs to pundit or not (as someone suggested, it does not belong there) - but independently of any metrics I like the idea because it would bundle security related ACL stuff together.

Another point is that it may be the case that different actions allow different attributes to be changed (e.g. some attribute that may be initially set in create but never changed with update).
Because of this I'd like to suggest that it would be useful to have a lookup chain which for action foo would first query ``foo_attributes`` and if that is not defined falls back to ``permitted_attributes``.
How about that? I'd probably give it a try if the maintainers agree.

**Comment by erlandsona** [comment]
For the thread I've since gotten rid of the super controller logic because it ended up being a bad fit to solve the problem I was facing...

That said, I did find a solid use case where I wanted to be able to submit top level parameters without having to define a root since the root was defined by the API endpoint itself it seemed redundant for any kind of querying... This makes it so you don't have to pass the instance of a new resource into permitted params to create logic for authorizing different params. And if you want the root back just use the standard Rails params.require(:root).permit(etc...) or just use the permitted attributes helper...

Maybe this isn't quite on topic but I would've loved to bette understand the Doc's on this helper with an example like this... Hope this helps someone else.

```ruby
class ResourceController < ApplicationController

  def create
    # .merge overrides user_id param this is only relevant if an admin
    # wants to create a resource specifying a different user as the creator.
    # The admin will have to create it as themselves then update it for the
    # user they want to own it if it's pending.
    @resource = Resource.new resource_params.merge(user_id: current_user.id)
    authorize @resource
    if @resource.save
      render json: @resource, status: 201, location: [:api, @resource]
    else
      render json: { errors: @resource.errors }, status: 422
    end
  end

  def update
    @resource = Resource.find params[:id]
    authorize @resource
    if @resource.update resource_params
      render json: @resource, status: 202, location: [:api, @resource]
    else
      render json: { errors: @resource.errors }, status: 422
    end
  end

  private

  def resource_params
    params.permit(policy(Resource).permitted_attributes)
  end

end
```

**Comment by jnicklas** [comment]
I think #340 is a nicer solution to some of the problems proposed in here. That being said, I don't think using a symbol is of any real advantage. It just makes it harder to write sensible policies and introduces one more way to do things for what I can see no real gain other than people thinking it looks kinda weird to send in an object.

I'd also really encourage people into *not* shoehorning things into the `permitted_attributes` helper. It's there as a neat shortcut *if* you are following the conventions exactly. I do not want to make it all powerful. I do not want to add a ton of options to id. Anyone who ever used something like inherited_resources or resource_controller should understand why this is a bad idea.
