### ISSUE TITLE
test and cached pundit policies

### ISSUE THREAD

**Issue by hachpai** [elabs/pundit#302]
Hi everyone,

I get a strange effect with pundit, I didn't run my test for a long time, and now some of them don't pass. When I debug, I see that my authlogic current user is the one specified by my test, but the returned policy has the previous one (chronologically in the tests).
````
  def policy(record)
    policies[record] ||= Pundit.policy!(pundit_user, record)
    #here I've pundit_user set correctly, but policies[record] return a policy initialized with another user fo the same record.
  end

...
  def policies
    @_pundit_policies ||= {}
  end
````
I hadn't that before, I've never written my tests according attention to cached policies. Any idea?

If I just modify the gem that way 
````
def policy(record)
    #policies[record] ||= Pundit.policy!(pundit_user, record)
    Pundit.policy!(pundit_user, record)
  end
````

My tests pass. Except controller index test. 

So, same problem with scope, i've just changed policy scope to avoid caching and now all my tests pass.

````
def pundit_policy_scope(scope)
    #policy_scopes[scope] ||= Pundit.policy_scope!(pundit_user, scope)
    Pundit.policy_scope!(pundit_user, scope)
  end
````
I think this will be limited to test environment but if not it's a critical issue.

**Comment by jnicklas** [comment]
Usually you'll include Pundit in your ApplicationController which will be fershly instantiated for each test. The cache shouldn't bleed over between tests. It could bleed over if you're doing something like setting instance variables on (could be by extending class with Pundit instead of including it) or storing instances somewhere. I know Authlogic stores stuff in thread-locals, are you sure it's cleared between tests?

**Comment by jnicklas** [comment]
No reply from OP. Closing.
