### ISSUE TITLE
Custom policy class resolver

### ISSUE THREAD

**Issue by pnomolos** [elabs/pundit#308]
What are your thoughts on having the ability to specify a custom proc/lambda/class to resolve the classes for a given policy?  For instance, the current app I'm working on has two separate user classes - one for the front-facing website (`Agent`) and one for the administration section (`AdminUser`).  However, they do end up administering the same classes, which can make building policies tricky because I now have to check the class of a passed-in `user`.  Having a custom resolver would let me have completely different classes to handle each user-type, rather than resorting to a bunch of hacks, so I could have these:

- `class AdminUser::OrderPolicy ... end`
- `class Agent::OrderPolicy ... end`

As I'm writing this, I realize I'd be content if there was simply a setting to namespace or prepend the class name of the `user` to the policy lookup.  My initial solution is _probably_ a bit overkill (although still an interesting idea, I suppose - if you were using a role-based auth scheme and the roles got quite complex you could break down policies according to role).

Thoughts?  I'd be willing to write an initial implementation of either of these if the idea has merit.

**Comment by jnicklas** [comment]
Namespaces have been suggested a bunch of times, but it's quite tricky to implement. We had a solution a while ago, but rolled it back because it didn't work properly in some edge cases. Someone also implemented a hacky fork of Pundit which does this, see https://github.com/coryodaniel/regulator, but I don't really understand how it's supposed to work.

As for a custom resolver, I think this is out of the scope for Pundit.

I'm not opposed to the idea of namespaces, in general, but the implementation needs to be airtight.

**Comment by pnomolos** [comment]
@jnicklas regulator does seem like overkill for what I'm doing.  Right now I'm just hoping for: 
  - "Does one of the following exist?"
  - `Agent::QuotePolicy` or `AdminUser::QuotePolicy`
  - If not, then use `QuotePolicy`

Any existing namespace support would be tacked on, so (and only if this is already working) if you had `SomeModule::Agent` and `SomeModule::QuotePolicy` the resolution would be to `SomeModule::Agent::SomeModule::QuotePolicy`, falling back to `SomeModule::QuotePolicy`.  No attempting to figure out that `SomeModule` refers to the same namespace.

Alternatively, what are your thoughts on using DI for the `PolicyFinder` class, so a user can specify a custom policy finder on their own (without having to clobber the existing class, though)?

**Comment by jnicklas** [comment]
The problem with that is that resolution should work wherever you are. Pundit explicitly encourages you to use policy finders in views as well, and it gets pretty tricky to figure out which object should map to which policy if there are tons of rules in play. Personally I would prefer there to be as little indirection as possible.

I think that if we're going to go down a path as heavy-handed as DI, it's easier to just code your custom policy helper in your app and make it whatever way you want to. If you really boil it down, Pundit is like 30LOC so replicating it exactly as you need should be easy.

**Comment by pnomolos** [comment]
@jnicklas My initial idea was that it'd be a setting on pundit, so by default you wouldn't get the "enhanced" rules.  That being said, I came up with a solution that works well for me without needing any changes to pundit - I'll just a general idea here in case anyone else runs into this situation:

```ruby
class PostPolicy
  def self.new(user, scope)
    user.is_a?(AdminUser) ? AdminUserPolicies::PostPolicy.new(user, scope) : RegularUserPolicies::PostPolicy.new(user, scope)
  end
end
```
And then, of course, define the other classes that you're using :smile:

**Comment by gamecreature** [comment]
I know this is an old question..
Currently the policy_scope method always calls 'resolve' on the pundit scope.
Why not making this method configurable?

Example:
```ruby
policy_scope(Post, :resolve_for_archive)
```
Instead of always calling the 'resolve' method on the scope, this calls the 'resolve_for_archive' method.

`policy_scope(Post)`

without argument equals to calling 

`policy_scope(Post, :resolve)`
