### ISSUE TITLE
Does Pundit support nested attributes in permitted_attributes?

### ISSUE THREAD

**Issue by fertingoff** [elabs/pundit#309]
Is it possible to use nested attributes in permitted attributes?
E.g. I have a `deal` and a `contact`. `deal` belongs to `contact` and `deal` accepts_nested_attributes_for `contact` in deal.rb. Usually I make update with:
```
params = {
  deal: {
    name: 'Foo',
    contact_attributes: {
      name: 'Bar',
      phone: '0110100110101001'
    }
  }
}
```
However, after installing pundit I'm getting `Unpermitted parameter: contact_attributes` error despite the fact that I added `contact_attributes` to array of Pundit's `permitted_attributes` method.

Does Pundit support nested attributes in permitted_attributes? If yes how I can switch it on, if not do you have any workaround for this issue of top of your head?

Thanks!

P.S. I have read  [guidelines for contributing](https://github.com/elabs/pundit/blob/master/CONTRIBUTING.md)  and did my best to find answer in issues and stackoverflow before ask this question.

**Comment by cireficc** [comment]
It may be that you are not including exactly what you need to. Consider this original controller permitted params:

    def deal_params
        # You must include the *nested* attributes for Contact in the permitted parameters
        params.require(:deal).permit(:name, conctact_attributes: [:id, :name, :phone])
    end

In your Pundit Policy class, probably `DealPolicy`, it should look something like this (though I haven't had to deal with nested parameters yet, I'm following the [documentation](https://github.com/elabs/pundit#strong-parameters)):

    class DealPolicy < ApplicationPolicy
        def permitted_attributes
            if user.admin? || user.owner_of?(deal)
                [:name, conctact_attributes: [:id, :name, :phone]]
            else
                [:whatever_else_a_non-admin_can_modify]
            end
        end
    end

Is that what your DealPolicy looks like? I haven't tested it, but it looks like the *strong parameters* mechanism works exactly the same so they should look very similar, whether through the original Rails controller design or through Pundit.

In either case, if you have an association in Rails and your form accepts nested attributes, they must follow the form:

    [...main object attributes..., XXXX_attributes: [array of nested object attributes]]

If you are still having trouble, you may consider asking on [StackOverflow](http://stackoverflow.com/) and pinging me here with another comment, and I will attempt to answer it (or maybe someone from the Pundit team will) :)

**Comment by fertingoff** [comment]
Excellent! Thank you so much. Please, close the issue.

P.S. And just for the records. As far as I understand there is no way to use `permit!.except(:id, :foo, :bar, ....)`, right? Would be really convenient.. (:

**Comment by cireficc** [comment]
@fertingoff So you got it working then? Awesome, glad to hear it :) I  can't personally close the issue because I didn't *open* it, nor am I a 'contributor' on the project. There should be a 'Close Issue' button directly to the left of the 'Comment' button. Perhaps only project contributors can close issues. I've never opened an issue on a project that I didn't own, so I'm not sure.

As for the `permit!.except` approach, yes, you can do that. It's called *blacklisting* instead of *whitelisting*, and is very useful when a model has an excessive number of attributes and only a few need to be protected.

You can do it in this fashion:

    params.require(:deal).permit!.except(:name)

If for example you wanted a contact to be able to update their information (such as `phone`) but not the actual `name` of the `deal`. The same should work if you want to blacklist something in `contact_attributes` as well:

    params.require(:deal).permit!.except(:name, contact_attributes: [:name])

The above would blacklist `name` in `deal` and `name` in `contact` while permitting all other attributes on both models. That's the normal Rails controller way to do it.

However, **I'm not sure how to do that in Pundit**, because Pundit seems to assume that you want `permitted_attributes` (hence the function name in your `Policy` class). Perhaps it is worth asking on StackOverflow, or opening an issue here. Let me know if you ask a question on StackOverflow so that I can star it!

**Comment by fertingoff** [comment]
Wow! Thank you for your prompt and uber_comprehensive response.
Yeah, good call. Here is my [question on StackOverflow] (http://stackoverflow.com/questions/32219310/does-pundit-support-blacklisting-for-attributes-inverse-for-permitted-attribute). Feel free to edit if you feel that it can be improved.

Thanks again, I'm closing the issue.

**Comment by SearchingSoul** [comment]
Just noticed something. Dont know if its a feature or a bug but wanted to leave a comment if it may help someone save time. 
Multiple if statements dont work it seems. I have various user types and each user type has some permitted attributes. I had to switch to elsif to make it work. 

following does not work
if user.type_a?
   [permitted parameters]
end
if user.type_b? 
  [permitted parameters]
end

**Comment by mtrolle** [comment]
@SearchingSoul that's due to how Ruby returns on a method.
In your current logic you'll always return the result of your last if statement., so if `user.type_b?` is not true, you end up returning `nil` - even though `user.type_a?` might be true.

Changing the logic to
````
if user.type_a?
  [permitted parameters]
elsif user.type_b?
  [permitted parameters]
end
````
will do the trick for you as you now only have on return value in the statement.

Alternatively you could explicitly return:
````
if user.type_a?
  return [permitted parameters]
end
if user.type_b?
  return [permitted parameters]
end
````
