### ISSUE TITLE
Authorizing Index views with nested resources?

### ISSUE THREAD

**Issue by AngelVillanueva** [elabs/pundit#324]
I can not figure out how to authorize the access to an Index view based on the parent resource.

User has_many :ideas
Idea belongs_to :user

resources :users do
  resources :ideas
end

Then I do not want a user to navigate to users/1/ideas if the user is not the one with id=1. Other words, if the user is not the ideas owner.

Any help would be very appreciated,
Best

**Comment by deefour** [comment]
One way is to create a stub `Idea` owned by the user to authorize against.

```ruby
def index
  @user = User::find(params[:user_id])
  idea  = Idea.new(user_id: @user.id)

  authorize idea

  # ...
end
```

Another way is to just change what you're looking at authorizing against. Instead of authorizing against `Idea`, authorize against the `User`.

```ruby
def index
  @user = User::find(params[:user_id])

  authorize @user, :show_ideas?

  # ...
end
```

and create a new `show_ideas?` method on your `UserPolicy`

```ruby
def show_ideas?
  user.id == record.id
end
```

**Comment by AngelVillanueva** [comment]
Exactly. It works perfectly. I prefer the second approach, more intuitive for me...

**Comment by ben-gy** [comment]
Hi - I have a question regarding this - I think I have found a suitable alternative solution (open to feedback)...

**Setup**
* I have a nested model
* I have a Location nested within is an Announcement
* I have a User that has many Locations
* The User should only be able to view the Announcements associated with the location
* In my AnnouncmentPolicy I have defined a "user" and a "record"

**Solution**
My index? method in the AnnouncementPolicy files looks like this.
```
  def index?
    user && record.pluck(:location_id).uniq.all? { |e| user.locations.pluck(:id).include?(e) }
  end
```

**Explanation**
* I am iterating through each record and grabbing the location id (they will all be the same because in my AnnouncementsController index method I am scoping the records ```@announcements = @location.announcements.order(updated_at: :desc)``` but for completeness I'll iterate through all instead of just the first record in the association)
* I am then iterating through each of the user's location's ids and ensuring all of the record location ids are included in the list of locations the user has a relationship to
