### ISSUE TITLE
List of permissions?

### ISSUE THREAD

**Issue by itsNikolay** [elabs/pundit#336]
Should a list of permissions be added to the gem?
For example:
```ruby
policy(@post).permissions
=> {
  index?: true,
  show?: true,
  update?: false,
  create?: false
}
```
It can be useful when need to show user's allowed actions in SPA application
(If it does, I would add them)

**Comment by jnicklas** [comment]
I think this is definitely something you can do in your application if it's useful to you, but I can't see what it is you would want to add to the gem itself? If you want this result to be generated automatically, that would involve some rather nasty metaprogramming which I'd rather avoid. Also, it's tricky since we don't have a common base class to jam this method into.

Overall, I'd say that this is not something we should do.

**Comment by mmahalwy** [comment]
👋 this thread is old but wanted to revive this to ask. Given how many apps exist relying on Rails API, getting permissions/rules on the frontend is pretty important. Thoughts about this now?

**Comment by januszm** [comment]
Few years later, same ask. And also related to the Rails API + Frontend problem, where UI (javascript) needs to know all the permissions user has or can have without code duplication.
