### ISSUE TITLE
Support for a model named 'Application'

### ISSUE THREAD

**Issue by cthielen** [elabs/pundit#358]
I have a Rails application with model names including 'Application', 'Role', 'Person', etc.

In my ApplicationsController#index I use "authorize Application" as I have no specific model of type Application in mind to authorize.

However, Pundit seems to imply that this should be checked against the 'ApplicationPolicy' which, if I understand correctly, is the designed to be the parent class of all policies.

Presumably I can just rename ApplicationPolicy to something like BasePolicy and then use ApplicationPolicy as a model-backed policy.

Any chance this could be avoided or is it an unfortunate consequence of having a model named 'Application' in Rails?

**Comment by damien** [comment]
I think you get around it by manually specifying the policy class you'd like to use. Since Pundit conventionally uses `ApplicationPolicy` it may be easier for you to use a different policy name and specify it manually as per [README - Manually Specifying Policy Classes](https://github.com/elabs/pundit#manually-specifying-policy-classes)

**Comment by cthielen** [comment]
Thanks, that works!

**Comment by damien** [comment]
:+1:
