### ISSUE TITLE
Policy is generated only once in a test with two GETs

### ISSUE THREAD

**Issue by cthielen** [elabs/pundit#366]
I'm using Pundit in a test which first attempts a GET against a controller action where current_user does not have the right. I confirm receiving a 403 from this GET then give current_user (in the database) the permission. I then perform another GET in the same commit but Pundit's policy class still has an old copy of the user. Reloading the ActiveRecord model will fix this.

Shouldn't Pundit be initializing a new policy instance for each GET/POST, etc. in a test to better simulate the real world?

**Comment by thomasklemm** [comment]
Sounds like no separate controller instance is being initialized between the two requests, as it would be with requests in development or production. That might be the reason why the memoized policy is being used. In real-world requests that memoization should not cause the issue you're describing.

An easy workaround for this might be separating the two requests into two separate test cases, so that for each case a new controller instance is instantiated.

**Comment by cthielen** [comment]
Thanks @thomasklemm , that's what I've gone ahead and done but for the future it might be best if pundit refreshes itself in whatever manner ActionController uses between these tests, or, if ActionController is also keeping instance around, perhaps we should file a bug with their team.

**Comment by jnicklas** [comment]
This is outside the scope of what Pundit should do. We are not in control of how Rails sets up its integration tests, and we definitely should not do anything to hack into that behaviour.
