### ISSUE TITLE
Potential improvement for verify_authorized

### ISSUE THREAD

**Issue by andresriancho** [elabs/pundit#404]
I was performing a security audit of a site using pundit and came across this exact scenario:

> What is this not?
> 
> It's not a failsafe for authorization. Imagine a scenario where there exists a controller action that mutates your service, e.g. PATCH /users/:id. Assuming the update action for the UsersController is not authorized, a request would result in a 500 error due to verify_authorized. However the update would already be persisted leaving a vector for updates being applied without proper authorization.

Which is described in the README section for `verify_authorized`.

I'm unsure about the performance / side-effects implications of this, but... can't pundit wrap all the request handling inside a **DB transaction** and "revert" / "prevent the commit" of any changes made during the controller method execution if `verify_authorized` fails?

**Comment by damien** [comment]
I'm not a maintainer, but that seems out of the scope of Pundit. This library doesn't provide any DB abstractions, just ruby objects. The implementation details of performing a database rollback will likely vary depending on your DB interface and what kind of DB (if any) someone is using.

**Comment by andresriancho** [comment]
@damien that does make sense. Maybe this could be implemented as a pundit "extension" (if that exists)?

**Comment by damien** [comment]
Wouldn't be surprised if that was the case. The wiki on this repo lists a number of them, if you haven't seen it already.

~ Damien

**Comment by idoan** [comment]
that description in scenario is really vague and missing. the bold text below must be added to the description:

"
...
a request would result in a 500 error due to verify_authorized. **Since verify_authorized is an after filter**,However, the update would already be persisted
....
"

**Comment by ce07c3** [comment]
This repo has a Wiki?

**Comment by jnicklas** [comment]
I can't think anything other than that this comes from a complete misunderstanding of what `verify_authorized` is supposed to do. It's not supposed to fail. Ever. If you ever get an `AuthorizationNotPerformed` error in production, you have done something seriously wrong.

It doesn't make sense to attach any fancy transaction or rollback or anything of the sort to it, since it's not supposed to fail in the first place.

Its only purpose is to be a reminder in case you forget to call `authorize`. That's it. 

Maybe we should suggest only adding this hook in development/test like this?

``` ruby
class ApplicationController < ActionController::Base
  include Pundit
  if Rails.env.test? or Rails.env.development?
    after_action :verify_authorized
  end
end
```
